#
# Copyright (c) 2021 Ford Motor Company
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

retroquest:
  security:
    require-https: false
    jwt-signing-secret: ASLKJHDKJHikjsdkjhg1iu2heiIUGEIUQ@IUeiUIU@iyrgiu2g3i # This is a default value. Ensure you override this value on any real deployments.
  app-base-url: something.com
  email:
    from-address: rq@fake.com
    is-enabled: true
    reset:
      token-lifetime-seconds: 600
  password:
    reset:
      token-lifetime-seconds: 600

spring:
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  liquibase:
    change-log: db/changelog.xml

server:
  error:
    include-message: always

logging.level:
  root: warn
  com.ford.labs.retroquest: info

springdoc:
  packages-to-scan: com.ford.labs.retroquest
