version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: retroquest
      POSTGRES_DB: retroquest
    ports:
      - "5432:5432"
