name: Build React
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - yeet-angular

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: cache gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: install ui dependencies
        working-directory: ./ui
        run: npm ci
      - name: build ui
        working-directory: ./ui
        run: |
          npm run update-version
          npm run build
      - name: build application JAR
        run: ./gradlew assemble withPostgres
      - name: release artifact
        uses: actions/upload-artifact@v2
        with:
          name: retroquest
          path: api/build/libs/retroquest.jar

      - name: cleanup gradle cache
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
